### ISSUE TITLE
NIP42 authentication

### ISSUE THREAD

**Issue by jeremyd** [0xchat-app/0xchat-core#12]
any plans to support NIP42 auth?

**Comment by water783** [comment]
I think it is supported. Is it not working?

**Comment by jeremyd** [comment]
Oh, I was attempting to test it earlier.  I setup 2 test accounts (but one was on amethyst) and I attempted regular DM, and NIP17 DM between them using this relay:  auth.nostr1.com

The relay is setup to only allow AUTH'd connections from any pubkey, and is open to all the necessary kinds..  But it will not allow any events without an AUTH.  I have run the same test with amethyst and it works there.   I looked at your NIP list and assumed it just wasn't implemented yet.

**Comment by water783** [comment]
Thank you for pointing that out. I think I didn't implement it correctly. I'll handle it in these days.

**Comment by jeremyd** [comment]
No problem, let me know if I can help debug.  You can use the auth relay if you want and let me know if you see any problems there and I can debug it.

**Comment by water783** [comment]
Are you using iOS? I have just updated the TestFlight version, you can have a try

**Comment by jeremyd** [comment]
I'm using android

**Comment by water783** [comment]
I just updated the APK. Feel free to give it a try!

https://github.com/0xchat-app/0xchat-app-main/releases/tag/v1.2.8-release

**Comment by jeremyd** [comment]
I tried 1.2.9, my relay is saying authentication is failed for the user.  It should be allowing any user to authenticate maybe sig is wrong?

**Comment by jeremyd** [comment]
hm, weird, I duno maybe my relay is not working.. it doesn't work in amethyst now either.  standby and i will attempt further debugging.

**Comment by jeremyd** [comment]
ok, i forgot i had the relay setup to only allow pubkeys from the list.  now that I have them, amethyst is working, but when I use 0x my relay is saying "err challenge tag missing from auth response".  There may be a bug in the challenge response from 0x?

**Comment by jeremyd** [comment]
I added your npub to the relay auth.nostr1.com if you want to try it

**Comment by water783** [comment]
I just tested this relay, and i can send DMs normally. @jeremyd

**Comment by water783** [comment]
Wait, I succeeded once, but others failed. Let me check

**Comment by water783** [comment]
i received notice: ["ERROR: bad msg: unknown cmd"], wss://auth.nostr1.com, what did it mean?

**Comment by jeremyd** [comment]
Did further testing:

I've seen this bad msg: unknown cmd, it also happens with amethyst.  I believe it means strfry does not recognize a REQ or something like this, but I'm unsure what strfry is seeing in this case.  Usually apps seem to still work..  Would be nice to track this down, I can possibly run with more debug logging, or if your client has debug of the request it was attempting to send that would be helpful.

The current behavior I'm seeing is that 0xChat looses it's socket connection when it is suspended (navigating to another app).  When resume, it does not attempt to re-establish the connection and does not attempt to login.

So when I send messages to it, it only shows if I force quit 0xchat, and re-open (by swiping up on the running app manager).  This way it establishes the connection, authenticates, and messages can be sent or received again.

A second thing I'm seeing, when I leave 0xChat open for a while (a few minutes), it seems to loose it's connection and attempt to re-auth, however the auth proxy is not receiving a proper challenge and saying "failed to validate AUTH event:  challenge tag missing from auth response"

I've opened up the auth relay to anyone with a pubkey now so it will be easier to test.  I'm unsure if this is my relay's implementation of auth, or the client or both... But I  have done extensive testing with amethyst and coracle and those clients seem to be able to send nip17 back and forth reliably without having to force quit or anything.

**Comment by jeremyd** [comment]
Ah, I think I've found part of the bug, somehow the AUTH is getting past my proxy and strfry sees it and returns BAD MSG: unknown CMD.  Ok, this could be bug on my side then because the proxy is supposed to be responding to those, not strfry.  Strfry should not be seeing the AUTH req at all..

**Comment by jeremyd** [comment]
Oh, actually, this makes sense if the client is sending multiple AUTHs on a connection that is already authenticated... So, from the proxy perspective, this was working as designed.. However I can modify it to drop these and then strfry will not send out the errors which may be tripping up a client..

**Comment by jeremyd** [comment]
Well, this is very strange, when I use 0xChat, my internal NIP42 parsing library keeps saying "challenge tag missing from auth response", but as far as I can tell, the challenge tag appears to be there.. This doesn't happen with the other clients and yet I see no noticeable difference in the response from 0x.  I will have to spend some time debugging this..

**Comment by jeremyd** [comment]
OH, ok, the challenge string that the relay is getting does not match the challenge it sent.  Somehow 0xChat is sending a wrong challenge string back.. this is strange because it's still in the same UUID format..  Is 0xChat opening multiple websocket connections at the same time possibly?  Each connection will have a unique challenge to that connection in this case and perhaps you are sending back a challenge string from a different connection.

**Comment by water783** [comment]
Thank you for your help. The tests on my side have passed. I have updated an APK. However, I was unable to reproduce the issue of reconnection that you mentioned. It might be related to different devices. I will continue to monitor this issue.

**Comment by water783** [comment]
https://github.com/0xchat-app/0xchat-app-main/releases/tag/v1.2.9-release

**Comment by jeremyd** [comment]
ok thank you, I was testing on the 1.2.9 apk if that helps.

**Comment by water783** [comment]
Are you using release2 APK, build 55?

**Comment by jeremyd** [comment]
mm, no I am using https://github.com/0xchat-app/0xchat-app-main/releases/tag/v1.2.9-release from 3 days ago.  I may look at spinning up a build environment for android but for now I am just testing the releases you linked to.

**Comment by water783** [comment]
Ah, The version from three days ago has a bug with repeated auth requests. So i updated the APK.

**Comment by jeremyd** [comment]
oh, im confused, the releases page says the release was updated 3 days ago?

**Comment by jeremyd** [comment]
OHHH, i see you updated 10 hours ago with release2. ok i will try this next

**Comment by jeremyd** [comment]
Ok I just did a quick test with the new APK.  It's working better now, however, there still seem to be connection issues when the app goes into the background or is open for too long.  When I force close it, and open, it receives the new messages.  Same for sending, sometimes if it's been in the background and then I try to send a new message, it says it sent, but it did not send.  I believe the connections are closing, and re-opening on resume but the app tries to subscribe and use them without responding/sending a new AUTH.

Another question I had is, does 0xchat publish kind 10050 private relay list?  Amethyst doesn't seem to be finding that, so it keeps defaulting back to kind4. (But I can still test nip17 by manually turning it back on).

**Comment by water783** [comment]
Regarding the connection issue, what phone are you using for testing? 

We have not published the private relay list, why is Amethyst switching to NIP-4? I need to check it.

**Comment by jeremyd** [comment]
I'm using a pixel 6 pro with latest android 14.  Yes amethyst needs that kind 10050 to automatically do nip17 (so does gossip).  Possibly coracle too but I haven't confirmed that.  I think all clients are starting to use it, at least those with nip17 support.

**Comment by water783** [comment]
Ahh thx, I will check it

**Comment by jeremyd** [comment]
I have discovered new information about how the current relay implementation is behaving.  It is disconnecting after 120s due to PING messages getting swallowed up by the middleware.  So, that means an app would need to re-connect, and this could be part of why things aren't working too well maintaining the connection.  It's a good stress test for apps, but I will likely adjust the settings to make this much higher, say 30m+, maybe even higher.  So, this means that whatever re-connection logic you have may be getting stalled out on the authing, and/or subscriptions not being re-subscribed when the disco happens.

Anyway, just fyi, I've been debugging the websockets on the relay with my NDK client..  NDK doesn't re-subscribe for example, but it does re-auth the connection on disco..

**Comment by water783** [comment]
Thank you for the information; it’s very helpful. We have a reconnection mechanism, and I don’t encounter this issue on my iOS device. However, I’m not sure why it doesn’t reconnect on your device. I need to further investigate the issue.

**Comment by water783** [comment]
I have fixed an issue with failing to receive DM messages, but I'm not sure if it's the same reason as yours. Let me test and see.

**Comment by jeremyd** [comment]
Hi @water783.  I've deployed another round of bugfixes to the relay.  I was mistakenly sending EOSE after the [REQ CLOSE "auth-required"] responses. I also was not responding properly to multiple AUTH responses.  These are now fixed.  

The general flow that this relay will perform (following NIP42 spec) is described here incase this is useful:

Initial connection.
Relay sends AUTH challenge.
If Client sends REQ or EVENT -> Relay re-sends AUTH challenge as well as [ok false "auth-required"] or [closed "auth-required"] in response to these until a successful AUTH response is received.
Client sends AUTH response.
Relay sends OK.
Connection is established to the backend for normal relay REQ/EVENTs.

**Comment by water783** [comment]
Awesome, thanks for your work. I will recommend your relay server in our inbox version.

**Comment by jeremyd** [comment]
Cool, no problem.  I tested the same version of 0xChat again with these changes but still seeing that in the background it looses connection.  When I force quit and open it again, it works.  Let me know when you have a new version and I can test that too.

**Comment by water783** [comment]
Sure, plan to release the inbox version next weekend.

**Comment by jeremyd** [comment]
Hey man!  good news, I found another bug in the relay implementation.  When receiving an event pre-auth i was sending ["OK", "theID", "false", ""]  as a string false, instead of bool ["OK, "theID", false, ""]  .. this may have been hanging up clients because it wasn't 'valid'.  Just wanted to let you know.  Fix is deployed..

**Comment by water783** [comment]
In our latest v1.3.0-beta version, does it work correctly?

**Comment by jeremyd** [comment]
i see the new beta versions, i will give it a test tomorrow!

**Comment by jeremyd** [comment]
I finally got around to doing a little bit of testing.  My initial findings is that it's working a bit better now I think.  Although here's what I'm seeing now:  I think 0xChat gets disconnected when it's open.  I open it, it finds the messages, and then send it a new message, but the message doesn't show up immediately.  But it re-connects eventually when you (regular) close/open it sometimes but not always..  Also on force close it opens and gets the latest messages..

going to keep testing over time here.. I have not yet tested other clients yet and did some more bug fixing on the relay for protected mode.  The relay is now set to keep inactive websockets open for 10 minutes (instead of 2 minutes before).

Another strange bug I've found is when I switched from using amber with my regular account (by deleting the account in 0xChat), to create/use a new testing account, it got confused and was still using amber (in addition to the new account?)  I was seeing messages from the main account in the new account..  so i revoked amber permission, and recreated the test account to make it work.

**Comment by jeremyd** [comment]
there may be a bug in the relay and not 0xChat..  i wrote a test for streaming with auth, and it also is not streaming the 1059s back, i will keep debugging and let you know what I find.

**Comment by jeremyd** [comment]
Okay, there was a bug in the relay with tracking logged in users across all the websockets.  This is working MUCH better now.  0xChat stays connected and it all seems good.  Thanks!  I will continue to test and make sure I don't have any more bugs on the relay side..  This was a major bug.  Whoops.
